# Generated by Django 4.0.1 on 2022-03-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_yearsofexperience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='YearsOfExperience',
            new_name='experience_in_years',
        ),
    ]
