# Generated by Django 4.0.1 on 2022-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=64)),
                ('field', models.CharField(choices=[('IT', 'Information Technology'), ('SL', 'Sales'), ('MG', 'Management'), ('AC', 'Analytics/Consulting'), ('OT', 'Other')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
