# Generated by Django 4.0.1 on 2022-03-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_name_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
