# Generated by Django 4.0.1 on 2022-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_lower',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
