# Generated by Django 4.0.1 on 2022-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_name_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_lower',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
