# Generated by Django 4.0.1 on 2022-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_name_lower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='company_name_case_insensitive',
        ),
    ]
